apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-
spec:
  pipelineRef:
    name: ci
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
  - name: git-credentials
    secret:
      secretName: git-credentials
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  params:
  - name: repo-url
    value: git@github.com:cyberphor/toughalien.git
  - name: image-reference
    value: cyberphorwashere.azurecr.io