---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  mode: daemonset
  env:
  - name: NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  config: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
      batch:
        send_batch_size: 10000
        timeout: 10s
    exporters:
      debug:
        verbosity: detailed
      otlp/elastic:
        endpoint: ${NODE_IP}:8200
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlp/elastic]
        metrics:
          receivers: [otlp]
          exporters: [debug, otlp/elastic]
        logs: 
          receivers: [otlp]
          exporters: [debug, otlp/elastic]
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"